const PING = "PING";
const NEW_USER = "NEW_USER";
const REGISTRATION_SUCCESS = "REGISTRATION_SUCCESS";
const LOGIN_SUCCESS = "LOGIN_SUCCESS";

module.exports = {
  PING,
  NEW_USER,
  REGISTRATION_SUCCESS,
  LOGIN_SUCCESS,
};
